[2022-07-06 15:43:24,794] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-07-06T15:43:05.674045+00:00 [queued]>
[2022-07-06 15:43:24,812] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: my_dag.inaccurate manual__2022-07-06T15:43:05.674045+00:00 [queued]>
[2022-07-06 15:43:24,814] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-06 15:43:24,816] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-06 15:43:24,817] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-06 15:43:24,883] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): inaccurate> on 2022-07-06 15:43:05.674045+00:00
[2022-07-06 15:43:24,891] {standard_task_runner.py:52} INFO - Started process 310 to run task
[2022-07-06 15:43:24,908] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2022-07-06T15:43:05.674045+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/my_ml_dag.py', '--cfg-path', '/tmp/tmp_zdd75_b', '--error-file', '/tmp/tmpz167onen']
[2022-07-06 15:43:24,909] {standard_task_runner.py:80} INFO - Job 34: Subtask inaccurate
[2022-07-06 15:43:25,170] {task_command.py:370} INFO - Running <TaskInstance: my_dag.inaccurate manual__2022-07-06T15:43:05.674045+00:00 [running]> on host fce85b9f2669
[2022-07-06 15:43:25,594] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=inaccurate
AIRFLOW_CTX_EXECUTION_DATE=2022-07-06T15:43:05.674045+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-06T15:43:05.674045+00:00
[2022-07-06 15:43:25,597] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-06 15:43:25,599] {subprocess.py:74} INFO - Running command: ['bash', '-c', "echo 'inaccurate'"]
[2022-07-06 15:43:25,649] {subprocess.py:85} INFO - Output:
[2022-07-06 15:43:25,653] {subprocess.py:92} INFO - inaccurate
[2022-07-06 15:43:25,654] {subprocess.py:96} INFO - Command exited with return code 0
[2022-07-06 15:43:25,796] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, execution_date=20220706T154305, start_date=20220706T154324, end_date=20220706T154325
[2022-07-06 15:43:25,873] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-06 15:43:25,915] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
